services:
  - type: web
    name: amberrjewelss
    env: static
    buildCommand: npm run build
    staticPublishPath: .next
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 